
package:
    name: boost-vpython
    version: 1.55.0

source:
    fn: boost_1_55_0.tar.bz2
    url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
    sha1: cef9a0cc7084b1d639e06cd3bc34e4251524c840

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python

test:
    imports:

about:
    home: http://www.boost.org/
    license: Boost-1.0

