package:
    name: vpython
    version: "6.11.0"

source:
    fn: v6.11.zip
    url: https://github.com/BruceSherwood/vpython-wx/archive/v6.11.zip
    patches:
        - vpython.patch   # [osx]
build:
    number: 0

requirements:
    build:
        - python
        - wxpython
        - numpy
        - boost-vpython
        - setuptools

    run:
        - python
        - polygon2
        - wxpython
        - boost-vpython
        - fonttools
        - ttfquery
        - numpy
