package:
    name: vpython
    version: "6.11.0"

source:
    fn: v6.11.zip
    url: https://github.com/BruceSherwood/vpython-wx/archive/v6.11.zip
    patches:
        - setup.patch   # [osx]
        - vidle.patch   # [osx]
        # NOTE: This recipe applies some patches in build.sh because of
        #       line ending issues.

build:
    number: 1

requirements:
    build:
        - python
        - wxpython
        - numpy
        - boost-vpython
        - setuptools

    run:
        - python
        - polygon2
        - wxpython
        - boost-vpython
        - fonttools
        - ttfquery
        - numpy
